# Generated by Django 3.2.18 on 2023-02-28 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('dui', models.CharField(max_length=15)),
                ('nit', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=25)),
                ('observacion', models.CharField(max_length=400)),
                ('tipo_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo', to='cobrox.tipo_cliente')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='zonas', to='cobrox.zona')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
