# Generated by Django 3.2.18 on 2023-03-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0003_auto_20230301_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('montootorgado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaini', models.DateField(help_text='Fecha de Inicio: YYYY-mm-dd')),
                ('fechaven', models.DateField(help_text='Fecha de Vencimiento: YYYY-mm-dd')),
                ('interespct', models.DecimalField(decimal_places=3, max_digits=6)),
                ('qtydiascuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capitalcuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interescuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalcuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuotaspagadas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuotaspendientes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldopendiente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipocredito', models.PositiveIntegerField(choices=[(0, 'CRÉDITO'), (1, 'REFINANCIAMIENTO')], help_text='Seleccione el Tipo de Crédito')),
                ('estadocredito', models.PositiveIntegerField(choices=[(0, 'VIGENTE'), (1, 'VENCIDO'), (2, 'CANCELADO')], help_text='Seleccione el Estado del Crédito')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clien', to='cobrox.cliente')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
