# Generated by Django 3.2.18 on 2023-03-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0004_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='interestotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credito',
            name='montoyinterestotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
