# Generated by Django 3.2.18 on 2023-03-03 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0006_auto_20230303_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recibo', models.CharField(max_length=10)),
                ('fecha', models.DateField(help_text='Fecha: YYYY-mm-dd')),
                ('tipoingreso', models.PositiveIntegerField(choices=[(0, 'RECIBO COBRO'), (1, 'REFINANCIAMIENTO')], help_text='Seleccione el Tipo de Ingreso')),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='credit', to='cobrox.credito')),
            ],
        ),
    ]
