# Generated by Django 3.2.18 on 2023-03-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0007_pagos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pagos',
            new_name='pago',
        ),
    ]
