# Generated by Django 3.2.18 on 2023-03-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0009_auto_20230304_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='nm_estado',
            field=models.IntegerField(choices=[(-1, 'INACTIVE'), (1, 'ACTIVE')], default=1, help_text='Activo o Inactivo el Registro'),
        ),
    ]
