# Generated by Django 3.2.18 on 2023-03-12 10:05

import cobrox.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0011_creditofinanc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='tipocredito',
            field=models.PositiveIntegerField(choices=[(0, 'CRÉDITO'), (1, 'REFINANC')], help_text='Seleccione el Tipo de Crédito'),
        ),
        migrations.CreateModel(
            name='credito_archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=cobrox.models.imagepacexp_directory_path_with_uuid)),
                ('nombre', models.CharField(help_text='Descripcion del nombre del archivo', max_length=400)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cobrox.credito')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='cliente_archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=cobrox.models.imagepacexp_directory_path_with_uuid)),
                ('nombre', models.CharField(help_text='Descripcion del nombre del archivo', max_length=400)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cobrox.cliente')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
