# Generated by Django 3.2.18 on 2023-03-12 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobrox', '0012_auto_20230312_1005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='credito_archivos',
            new_name='cliente_archivo',
        ),
        migrations.RenameModel(
            old_name='cliente_archivos',
            new_name='credito_archivo',
        ),
        migrations.RemoveField(
            model_name='cliente_archivo',
            name='credito',
        ),
        migrations.RemoveField(
            model_name='credito_archivo',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cliente_archivo',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cobrox.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credito_archivo',
            name='credito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cobrox.credito'),
            preserve_default=False,
        ),
    ]
